create database givemethegoods;
use givemethegoods;
create table Students (
	id INT,
	city VARCHAR(50),
	country VARCHAR(50),
	gender VARCHAR(50)
);
insert into Students (id, city, country, gender) values (1, 'Bahía Blanca', 'Argentina', 'Female');
insert into Students (id, city, country, gender) values (2, 'Kemijärvi', 'Finland', 'Female');
insert into Students (id, city, country, gender) values (3, 'Huaccana', 'Peru', 'Male');
insert into Students (id, city, country, gender) values (4, 'Targowisko', 'Poland', 'Female');
insert into Students (id, city, country, gender) values (5, 'Yalukou', 'China', 'Male');
insert into Students (id, city, country, gender) values (6, 'Nagua', 'Dominican Republic', 'Male');
insert into Students (id, city, country, gender) values (7, 'Ancasti', 'Argentina', 'Male');
insert into Students (id, city, country, gender) values (8, 'Huaqiao', 'China', 'Female');
insert into Students (id, city, country, gender) values (9, 'Hondo Valle', 'Dominican Republic', 'Male');
insert into Students (id, city, country, gender) values (10, 'Zhugentan', 'China', 'Female');
insert into Students (id, city, country, gender) values (11, 'Santa Rosa', 'Mexico', 'Male');
insert into Students (id, city, country, gender) values (12, 'Ingenio', 'Peru', 'Male');
insert into Students (id, city, country, gender) values (13, 'Bayt Dajan', 'Palestinian Territory', 'Male');
insert into Students (id, city, country, gender) values (14, 'Pacatuba', 'Brazil', 'Male');
insert into Students (id, city, country, gender) values (15, 'Nong Khai', 'Thailand', 'Female');
insert into Students (id, city, country, gender) values (16, 'Kamensk-Shakhtinskiy', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (17, 'Paseh', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (18, 'Kemiri Daya', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (19, 'Hyrynsalmi', 'Finland', 'Male');
insert into Students (id, city, country, gender) values (20, 'Krajan Puru', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (21, 'Ojrzeń', 'Poland', 'Male');
insert into Students (id, city, country, gender) values (22, 'Balitai', 'China', 'Female');
insert into Students (id, city, country, gender) values (23, 'Tanghua', 'China', 'Female');
insert into Students (id, city, country, gender) values (24, 'Itsukaichi', 'Japan', 'Male');
insert into Students (id, city, country, gender) values (25, 'Floreşti', 'Moldova', 'Female');
insert into Students (id, city, country, gender) values (26, 'Jamaica', 'United States', 'Female');
insert into Students (id, city, country, gender) values (27, 'Växjö', 'Sweden', 'Male');
insert into Students (id, city, country, gender) values (28, 'Kryvyy Rih', 'Ukraine', 'Male');
insert into Students (id, city, country, gender) values (29, 'Quxia', 'China', 'Male');
insert into Students (id, city, country, gender) values (30, 'Zavety Il’icha', 'Russia', 'Female');
insert into Students (id, city, country, gender) values (31, 'Malianchuan', 'China', 'Male');
insert into Students (id, city, country, gender) values (32, 'Xinhe', 'China', 'Female');
insert into Students (id, city, country, gender) values (33, 'Néa Ankhíalos', 'Greece', 'Male');
insert into Students (id, city, country, gender) values (34, 'Farinheiras', 'Portugal', 'Male');
insert into Students (id, city, country, gender) values (35, 'São José do Rio Pardo', 'Brazil', 'Male');
insert into Students (id, city, country, gender) values (36, 'Arauco', 'Chile', 'Male');
insert into Students (id, city, country, gender) values (37, 'Biggar', 'Canada', 'Female');
insert into Students (id, city, country, gender) values (38, 'Hōjō', 'Japan', 'Female');
insert into Students (id, city, country, gender) values (39, 'Gereneng', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (40, 'Tomelilla', 'Sweden', 'Male');
insert into Students (id, city, country, gender) values (41, 'San José de Bocay', 'Nicaragua', 'Male');
insert into Students (id, city, country, gender) values (42, 'São Marcos da Serra', 'Portugal', 'Female');
insert into Students (id, city, country, gender) values (43, 'Budapest', 'Hungary', 'Female');
insert into Students (id, city, country, gender) values (44, 'Saint-Lambert-de-Lauzon', 'Canada', 'Male');
insert into Students (id, city, country, gender) values (45, 'Malandag', 'Philippines', 'Female');
insert into Students (id, city, country, gender) values (46, 'San José del Guaviare', 'Colombia', 'Female');
insert into Students (id, city, country, gender) values (47, 'Hartswater', 'South Africa', 'Female');
insert into Students (id, city, country, gender) values (48, 'Jianghai', 'China', 'Female');
insert into Students (id, city, country, gender) values (49, 'Stari Grad', 'Croatia', 'Male');
insert into Students (id, city, country, gender) values (50, 'Kołbiel', 'Poland', 'Female');
insert into Students (id, city, country, gender) values (51, 'Inyati', 'Zimbabwe', 'Male');
insert into Students (id, city, country, gender) values (52, 'Munggang', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (53, 'Gornyy', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (54, 'Sawaengha', 'Thailand', 'Female');
insert into Students (id, city, country, gender) values (55, 'Labao', 'China', 'Male');
insert into Students (id, city, country, gender) values (56, 'Zhiqu', 'China', 'Female');
insert into Students (id, city, country, gender) values (57, 'Lanling', 'China', 'Female');
insert into Students (id, city, country, gender) values (58, 'Andong', 'South Korea', 'Male');
insert into Students (id, city, country, gender) values (59, 'Sanlifan', 'China', 'Female');
insert into Students (id, city, country, gender) values (60, 'Shahrak', 'Afghanistan', 'Female');
insert into Students (id, city, country, gender) values (61, 'Laocheng', 'China', 'Female');
insert into Students (id, city, country, gender) values (62, 'Sartana', 'Ukraine', 'Male');
insert into Students (id, city, country, gender) values (63, 'Blama', 'Sierra Leone', 'Female');
insert into Students (id, city, country, gender) values (64, 'Watulabara', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (65, 'Mattawa', 'Canada', 'Female');
insert into Students (id, city, country, gender) values (66, 'Chorotis', 'Argentina', 'Male');
insert into Students (id, city, country, gender) values (67, 'Mīrābād', 'Afghanistan', 'Female');
insert into Students (id, city, country, gender) values (68, 'San Agustín', 'Colombia', 'Female');
insert into Students (id, city, country, gender) values (69, 'Mibu', 'Japan', 'Female');
insert into Students (id, city, country, gender) values (70, 'Makedonski Brod', 'Macedonia', 'Male');
insert into Students (id, city, country, gender) values (71, 'Panenjoan', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (72, 'Hongguang', 'China', 'Female');
insert into Students (id, city, country, gender) values (73, 'Kashirskoye', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (74, 'Glushkovo', 'Russia', 'Female');
insert into Students (id, city, country, gender) values (75, 'Hushaat', 'Mongolia', 'Female');
insert into Students (id, city, country, gender) values (76, 'Yangmadao', 'China', 'Female');
insert into Students (id, city, country, gender) values (77, 'Addiet Canna', 'Ethiopia', 'Female');
insert into Students (id, city, country, gender) values (78, 'Chunoyar', 'Russia', 'Female');
insert into Students (id, city, country, gender) values (79, 'Van Nuys', 'United States', 'Male');
insert into Students (id, city, country, gender) values (80, 'Sanana', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (81, 'Baghdad', 'Iraq', 'Female');
insert into Students (id, city, country, gender) values (82, 'Yichun', 'China', 'Male');
insert into Students (id, city, country, gender) values (83, 'Mishima', 'Japan', 'Female');
insert into Students (id, city, country, gender) values (84, 'Areni', 'Armenia', 'Female');
insert into Students (id, city, country, gender) values (85, 'Nangxian', 'China', 'Male');
insert into Students (id, city, country, gender) values (86, 'Néos Skopós', 'Greece', 'Male');
insert into Students (id, city, country, gender) values (87, 'Basseterre', 'Saint Kitts and Nevis', 'Male');
insert into Students (id, city, country, gender) values (88, 'Runka', 'Nigeria', 'Male');
insert into Students (id, city, country, gender) values (89, 'Zaleszany', 'Poland', 'Female');
insert into Students (id, city, country, gender) values (90, 'Hexi', 'China', 'Male');
insert into Students (id, city, country, gender) values (91, 'Meizhou', 'China', 'Female');
insert into Students (id, city, country, gender) values (92, 'Torre de Moncorvo', 'Portugal', 'Female');
insert into Students (id, city, country, gender) values (93, 'Alexandria', 'United States', 'Female');
insert into Students (id, city, country, gender) values (94, 'Kiełczów', 'Poland', 'Male');
insert into Students (id, city, country, gender) values (95, 'San Jorge', 'Argentina', 'Female');
insert into Students (id, city, country, gender) values (96, 'Cimalati', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (97, 'Francisco Villa', 'Mexico', 'Female');
insert into Students (id, city, country, gender) values (98, 'Xiaoshiqiao', 'China', 'Female');
insert into Students (id, city, country, gender) values (99, 'Pokrov', 'Russia', 'Female');
insert into Students (id, city, country, gender) values (100, 'Pidvolochys’k', 'Ukraine', 'Male');
insert into Students (id, city, country, gender) values (101, 'Kebon', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (102, 'Sutukoba', 'Gambia', 'Male');
insert into Students (id, city, country, gender) values (103, 'Gabasumdo', 'China', 'Female');
insert into Students (id, city, country, gender) values (104, 'Gaspar', 'Brazil', 'Female');
insert into Students (id, city, country, gender) values (105, 'Mariposa', 'Peru', 'Male');
insert into Students (id, city, country, gender) values (106, 'Patsi', 'Comoros', 'Female');
insert into Students (id, city, country, gender) values (107, 'Brušperk', 'Czech Republic', 'Male');
insert into Students (id, city, country, gender) values (108, 'Tottori', 'Japan', 'Male');
insert into Students (id, city, country, gender) values (109, 'Rosice', 'Czech Republic', 'Female');
insert into Students (id, city, country, gender) values (110, 'Dizangué', 'Cameroon', 'Male');
insert into Students (id, city, country, gender) values (111, 'Koloniya Zastav’ye', 'Ukraine', 'Female');
insert into Students (id, city, country, gender) values (112, 'Hejiabao', 'China', 'Female');
insert into Students (id, city, country, gender) values (113, 'Yumaguzino', 'Russia', 'Female');
insert into Students (id, city, country, gender) values (114, 'Mādārīpur', 'Bangladesh', 'Female');
insert into Students (id, city, country, gender) values (115, 'Nanjing', 'China', 'Female');
insert into Students (id, city, country, gender) values (116, 'Ridder', 'Kazakhstan', 'Male');
insert into Students (id, city, country, gender) values (117, 'Gastello', 'Russia', 'Female');
insert into Students (id, city, country, gender) values (118, 'Aurora', 'United States', 'Female');
insert into Students (id, city, country, gender) values (119, 'Tullinge', 'Sweden', 'Male');
insert into Students (id, city, country, gender) values (120, 'Aparecida do Taboado', 'Brazil', 'Female');
insert into Students (id, city, country, gender) values (121, 'Tarasovskiy', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (122, 'Jiefu', 'China', 'Female');
insert into Students (id, city, country, gender) values (123, 'Ngembel', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (124, 'Cergy-Pontoise', 'France', 'Female');
insert into Students (id, city, country, gender) values (125, 'Nybro', 'Sweden', 'Male');
insert into Students (id, city, country, gender) values (126, 'Botigues', 'Philippines', 'Male');
insert into Students (id, city, country, gender) values (127, 'Dallas', 'United States', 'Male');
insert into Students (id, city, country, gender) values (128, 'Pandian', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (129, 'Santa Elena de Uairén', 'Venezuela', 'Male');
insert into Students (id, city, country, gender) values (130, 'Shedok', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (131, 'Yangyu', 'China', 'Female');
insert into Students (id, city, country, gender) values (132, 'Springfield', 'United States', 'Female');
insert into Students (id, city, country, gender) values (133, 'Mburukullu', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (134, 'Periyiáli', 'Greece', 'Male');
insert into Students (id, city, country, gender) values (135, 'Huoshaodian', 'China', 'Male');
insert into Students (id, city, country, gender) values (136, 'Río Gallegos', 'Argentina', 'Female');
insert into Students (id, city, country, gender) values (137, 'Xinghai', 'China', 'Male');
insert into Students (id, city, country, gender) values (138, 'Cacaopera', 'El Salvador', 'Male');
insert into Students (id, city, country, gender) values (139, 'Buga', 'Colombia', 'Male');
insert into Students (id, city, country, gender) values (140, 'Pameungpeuk', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (141, 'Mayapusi', 'Philippines', 'Female');
insert into Students (id, city, country, gender) values (142, 'Kyaikkami', 'Myanmar', 'Male');
insert into Students (id, city, country, gender) values (143, 'Tolosa', 'Philippines', 'Female');
insert into Students (id, city, country, gender) values (144, 'Quyangqiao', 'China', 'Female');
insert into Students (id, city, country, gender) values (145, 'Modderfontein', 'South Africa', 'Male');
insert into Students (id, city, country, gender) values (146, 'Praingkareha', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (147, 'Rakszawa', 'Poland', 'Female');
insert into Students (id, city, country, gender) values (148, 'Legrada', 'Philippines', 'Male');
insert into Students (id, city, country, gender) values (149, 'Golek', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (150, 'Tubel', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (151, 'Krasnyy Oktyabr’', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (152, 'Głuchołazy', 'Poland', 'Female');
insert into Students (id, city, country, gender) values (153, 'Sebu', 'Philippines', 'Female');
insert into Students (id, city, country, gender) values (154, 'Karangpao', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (155, 'Ta Khmau', 'Cambodia', 'Male');
insert into Students (id, city, country, gender) values (156, 'Jingyu', 'China', 'Male');
insert into Students (id, city, country, gender) values (157, 'Leiwang', 'China', 'Female');
insert into Students (id, city, country, gender) values (158, 'Lascano', 'Uruguay', 'Female');
insert into Students (id, city, country, gender) values (159, 'Uyutne', 'Ukraine', 'Female');
insert into Students (id, city, country, gender) values (160, 'Alcala', 'Philippines', 'Female');
insert into Students (id, city, country, gender) values (161, 'Campoalegre', 'Colombia', 'Male');
insert into Students (id, city, country, gender) values (162, 'Kavajë', 'Albania', 'Female');
insert into Students (id, city, country, gender) values (163, 'Vršac', 'Serbia', 'Female');
insert into Students (id, city, country, gender) values (164, 'Bebedouro', 'Brazil', 'Male');
insert into Students (id, city, country, gender) values (165, 'Pan-an', 'Philippines', 'Female');
insert into Students (id, city, country, gender) values (166, 'Okayama-shi', 'Japan', 'Male');
insert into Students (id, city, country, gender) values (167, 'Wuhu', 'China', 'Male');
insert into Students (id, city, country, gender) values (168, 'Madrid', 'Colombia', 'Male');
insert into Students (id, city, country, gender) values (169, 'Waco', 'United States', 'Male');
insert into Students (id, city, country, gender) values (170, 'Kamennogorsk', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (171, 'Rathdrum', 'Ireland', 'Male');
insert into Students (id, city, country, gender) values (172, 'Algés', 'Portugal', 'Male');
insert into Students (id, city, country, gender) values (173, 'Boudinar', 'Morocco', 'Male');
insert into Students (id, city, country, gender) values (174, 'Bajiazi', 'China', 'Male');
insert into Students (id, city, country, gender) values (175, 'Austin', 'United States', 'Female');
insert into Students (id, city, country, gender) values (176, 'Beishan', 'China', 'Female');
insert into Students (id, city, country, gender) values (177, 'Loreto', 'Argentina', 'Female');
insert into Students (id, city, country, gender) values (178, 'Mikrókampos', 'Greece', 'Male');
insert into Students (id, city, country, gender) values (179, 'Tyresö', 'Sweden', 'Female');
insert into Students (id, city, country, gender) values (180, 'Janakkala', 'Finland', 'Male');
insert into Students (id, city, country, gender) values (181, 'Lorient', 'France', 'Male');
insert into Students (id, city, country, gender) values (182, 'Fažana', 'Croatia', 'Female');
insert into Students (id, city, country, gender) values (183, 'Tulcán', 'Ecuador', 'Female');
insert into Students (id, city, country, gender) values (184, 'Hammam-Lif', 'Tunisia', 'Female');
insert into Students (id, city, country, gender) values (185, 'Zhoukou', 'China', 'Male');
insert into Students (id, city, country, gender) values (186, 'Ganpu', 'China', 'Female');
insert into Students (id, city, country, gender) values (187, 'Hongjiaguan', 'China', 'Female');
insert into Students (id, city, country, gender) values (188, 'Paghmān', 'Afghanistan', 'Male');
insert into Students (id, city, country, gender) values (189, 'Chefchaouene', 'Morocco', 'Male');
insert into Students (id, city, country, gender) values (190, 'El Refugio', 'Mexico', 'Female');
insert into Students (id, city, country, gender) values (191, 'El Paso', 'United States', 'Male');
insert into Students (id, city, country, gender) values (192, 'Sancha', 'China', 'Male');
insert into Students (id, city, country, gender) values (193, 'Nowe Miasto', 'Poland', 'Female');
insert into Students (id, city, country, gender) values (194, 'Santa Magdalena', 'Philippines', 'Female');
insert into Students (id, city, country, gender) values (195, 'Harrison', 'Philippines', 'Female');
insert into Students (id, city, country, gender) values (196, 'Cagayan', 'Philippines', 'Female');
insert into Students (id, city, country, gender) values (197, 'Sila Lat', 'Thailand', 'Male');
insert into Students (id, city, country, gender) values (198, 'Rendian', 'China', 'Male');
insert into Students (id, city, country, gender) values (199, 'Mauloo', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (200, 'Ráječko', 'Czech Republic', 'Female');
insert into Students (id, city, country, gender) values (201, 'Tunasbaru', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (202, 'Pęczniew', 'Poland', 'Male');
insert into Students (id, city, country, gender) values (203, 'Shuanghejiedao', 'China', 'Male');
insert into Students (id, city, country, gender) values (204, 'Jinhe', 'China', 'Male');
insert into Students (id, city, country, gender) values (205, 'Siquirres', 'Costa Rica', 'Male');
insert into Students (id, city, country, gender) values (206, 'Socorro', 'Philippines', 'Male');
insert into Students (id, city, country, gender) values (207, 'Longwantun', 'China', 'Female');
insert into Students (id, city, country, gender) values (208, 'Adiaké', 'Ivory Coast', 'Female');
insert into Students (id, city, country, gender) values (209, 'Paranapanema', 'Brazil', 'Male');
insert into Students (id, city, country, gender) values (210, 'Pantanal', 'Brazil', 'Female');
insert into Students (id, city, country, gender) values (211, 'Dehui', 'China', 'Female');
insert into Students (id, city, country, gender) values (212, 'Mehtar Lām', 'Afghanistan', 'Female');
insert into Students (id, city, country, gender) values (213, 'Wuyang', 'China', 'Female');
insert into Students (id, city, country, gender) values (214, 'Longxi', 'China', 'Female');
insert into Students (id, city, country, gender) values (215, 'Ruzhany', 'Belarus', 'Male');
insert into Students (id, city, country, gender) values (216, 'Unaí', 'Brazil', 'Male');
insert into Students (id, city, country, gender) values (217, 'Valuyki', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (218, 'Fort Worth', 'United States', 'Male');
insert into Students (id, city, country, gender) values (219, 'Shaochang', 'China', 'Female');
insert into Students (id, city, country, gender) values (220, 'Bay Roberts', 'Canada', 'Male');
insert into Students (id, city, country, gender) values (221, 'Kairouan', 'Tunisia', 'Male');
insert into Students (id, city, country, gender) values (222, 'Illushi', 'Nigeria', 'Male');
insert into Students (id, city, country, gender) values (223, 'Iberia', 'Peru', 'Female');
insert into Students (id, city, country, gender) values (224, 'José Bonifácio', 'Brazil', 'Female');
insert into Students (id, city, country, gender) values (225, 'Siparia', 'Trinidad and Tobago', 'Female');
insert into Students (id, city, country, gender) values (226, 'Austin', 'United States', 'Female');
insert into Students (id, city, country, gender) values (227, 'Fuji', 'Japan', 'Male');
insert into Students (id, city, country, gender) values (228, 'Ossora', 'Russia', 'Female');
insert into Students (id, city, country, gender) values (229, 'Cercal', 'Portugal', 'Male');
insert into Students (id, city, country, gender) values (230, 'Hebei', 'China', 'Female');
insert into Students (id, city, country, gender) values (231, 'Tairan Camp', 'Philippines', 'Female');
insert into Students (id, city, country, gender) values (232, 'Lughaye', 'Somalia', 'Female');
insert into Students (id, city, country, gender) values (233, 'Jönköping', 'Sweden', 'Male');
insert into Students (id, city, country, gender) values (234, 'Tsagaan-Owoo', 'Mongolia', 'Female');
insert into Students (id, city, country, gender) values (235, 'Granada', 'Spain', 'Male');
insert into Students (id, city, country, gender) values (236, 'Krasnokamsk', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (237, 'Outlook', 'Canada', 'Male');
insert into Students (id, city, country, gender) values (238, 'Mendī', 'Ethiopia', 'Female');
insert into Students (id, city, country, gender) values (239, 'København', 'Denmark', 'Male');
insert into Students (id, city, country, gender) values (240, 'Gelan', 'China', 'Female');
insert into Students (id, city, country, gender) values (241, 'Santos Dumont', 'Brazil', 'Male');
insert into Students (id, city, country, gender) values (242, 'Dao', 'Philippines', 'Female');
insert into Students (id, city, country, gender) values (243, 'São José do Rio Pardo', 'Brazil', 'Female');
insert into Students (id, city, country, gender) values (244, 'Bodø', 'Norway', 'Female');
insert into Students (id, city, country, gender) values (245, 'Los Guayos', 'Venezuela', 'Female');
insert into Students (id, city, country, gender) values (246, 'Mosina', 'Poland', 'Female');
insert into Students (id, city, country, gender) values (247, 'General Enrique Godoy', 'Argentina', 'Male');
insert into Students (id, city, country, gender) values (248, 'Chengyang', 'China', 'Female');
insert into Students (id, city, country, gender) values (249, 'Suban', 'China', 'Female');
insert into Students (id, city, country, gender) values (250, 'Bagroy', 'Philippines', 'Male');
insert into Students (id, city, country, gender) values (251, 'Pont Cassé', 'Dominica', 'Female');
insert into Students (id, city, country, gender) values (252, 'Domartang', 'China', 'Female');
insert into Students (id, city, country, gender) values (253, 'Xiaopu', 'China', 'Male');
insert into Students (id, city, country, gender) values (254, 'Szombathely', 'Hungary', 'Male');
insert into Students (id, city, country, gender) values (255, 'Klakeh', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (256, 'Arras', 'France', 'Female');
insert into Students (id, city, country, gender) values (257, 'Bājitpur', 'Bangladesh', 'Female');
insert into Students (id, city, country, gender) values (258, 'Yanacancha', 'Peru', 'Female');
insert into Students (id, city, country, gender) values (259, 'Puerto Aisén', 'Chile', 'Male');
insert into Students (id, city, country, gender) values (260, 'Malanday', 'Philippines', 'Female');
insert into Students (id, city, country, gender) values (261, 'Wonokerto', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (262, 'Warburton', 'Pakistan', 'Male');
insert into Students (id, city, country, gender) values (263, 'Hinapalanan', 'Philippines', 'Male');
insert into Students (id, city, country, gender) values (264, 'Beutong Ateuh', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (265, 'Rosebank', 'South Africa', 'Female');
insert into Students (id, city, country, gender) values (266, 'Ta’ Xbiex', 'Malta', 'Female');
insert into Students (id, city, country, gender) values (267, 'Majan', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (268, 'Bandar Pusat Jengka', 'Malaysia', 'Female');
insert into Students (id, city, country, gender) values (269, 'Wako', 'Japan', 'Female');
insert into Students (id, city, country, gender) values (270, 'Shanxia', 'China', 'Female');
insert into Students (id, city, country, gender) values (271, 'Pandansari', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (272, 'Barishāl', 'Pakistan', 'Female');
insert into Students (id, city, country, gender) values (273, 'Pajé', 'Comoros', 'Female');
insert into Students (id, city, country, gender) values (274, 'Thap Than', 'Thailand', 'Female');
insert into Students (id, city, country, gender) values (275, 'Tatarka', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (276, 'Dobrljin', 'Bosnia and Herzegovina', 'Male');
insert into Students (id, city, country, gender) values (277, 'Kallífytos', 'Greece', 'Female');
insert into Students (id, city, country, gender) values (278, 'Pivovarikha', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (279, 'Aparecida do Taboado', 'Brazil', 'Female');
insert into Students (id, city, country, gender) values (280, 'Ciusul', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (281, 'Bherāmāra', 'Bangladesh', 'Female');
insert into Students (id, city, country, gender) values (282, 'Trollhättan', 'Sweden', 'Male');
insert into Students (id, city, country, gender) values (283, 'Suocheng', 'China', 'Female');
insert into Students (id, city, country, gender) values (284, 'Wudong', 'China', 'Female');
insert into Students (id, city, country, gender) values (285, 'Shengping', 'China', 'Female');
insert into Students (id, city, country, gender) values (286, 'Kalungu', 'Uganda', 'Female');
insert into Students (id, city, country, gender) values (287, 'Nāḩiyat Hīrān', 'Iraq', 'Male');
insert into Students (id, city, country, gender) values (288, 'Chistopol’', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (289, 'Sitangkai', 'Philippines', 'Male');
insert into Students (id, city, country, gender) values (290, 'Damiao', 'China', 'Male');
insert into Students (id, city, country, gender) values (291, 'Korydallós', 'Greece', 'Male');
insert into Students (id, city, country, gender) values (292, 'Agía Varvára', 'Greece', 'Male');
insert into Students (id, city, country, gender) values (293, 'Särevere', 'Estonia', 'Male');
insert into Students (id, city, country, gender) values (294, 'Nashville', 'United States', 'Male');
insert into Students (id, city, country, gender) values (295, 'San Jacinto', 'Peru', 'Male');
insert into Students (id, city, country, gender) values (296, 'Shirochanka', 'Russia', 'Female');
insert into Students (id, city, country, gender) values (297, 'Quỳnh Côi', 'Vietnam', 'Male');
insert into Students (id, city, country, gender) values (298, 'Kengyuan', 'China', 'Male');
insert into Students (id, city, country, gender) values (299, 'Siverskiy', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (300, 'Abha', 'Saudi Arabia', 'Female');
insert into Students (id, city, country, gender) values (301, 'Carrasqueira', 'Portugal', 'Female');
insert into Students (id, city, country, gender) values (302, 'Castanheira do Campo', 'Portugal', 'Male');
insert into Students (id, city, country, gender) values (303, 'Yarumela', 'Honduras', 'Male');
insert into Students (id, city, country, gender) values (304, 'Panjgūr', 'Pakistan', 'Male');
insert into Students (id, city, country, gender) values (305, 'Paris 15', 'France', 'Male');
insert into Students (id, city, country, gender) values (306, 'Kyra', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (307, 'Maying', 'China', 'Male');
insert into Students (id, city, country, gender) values (308, 'Ansermanuevo', 'Colombia', 'Female');
insert into Students (id, city, country, gender) values (309, 'Nanjie', 'China', 'Male');
insert into Students (id, city, country, gender) values (310, 'Aranđelovac', 'Serbia', 'Female');
insert into Students (id, city, country, gender) values (311, 'Necochea', 'Argentina', 'Male');
insert into Students (id, city, country, gender) values (312, 'Songjianghe', 'China', 'Female');
insert into Students (id, city, country, gender) values (313, 'Zhaotong', 'China', 'Female');
insert into Students (id, city, country, gender) values (314, 'Yinping', 'China', 'Female');
insert into Students (id, city, country, gender) values (315, 'Siilinjärvi', 'Finland', 'Female');
insert into Students (id, city, country, gender) values (316, 'Limoges', 'France', 'Male');
insert into Students (id, city, country, gender) values (317, 'Kaducondong', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (318, 'Borek', 'Poland', 'Female');
insert into Students (id, city, country, gender) values (319, 'Cork', 'Ireland', 'Male');
insert into Students (id, city, country, gender) values (320, 'Charleville-Mézières', 'France', 'Male');
insert into Students (id, city, country, gender) values (321, 'Пласница', 'Macedonia', 'Female');
insert into Students (id, city, country, gender) values (322, 'Pshada', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (323, 'Kāleke Mandi', 'Pakistan', 'Female');
insert into Students (id, city, country, gender) values (324, 'Maikawada', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (325, 'Sukamaju Kidul', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (326, 'Tomari', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (327, 'Jadowniki Mokre', 'Poland', 'Female');
insert into Students (id, city, country, gender) values (328, 'Ferraz de Vasconcelos', 'Brazil', 'Male');
insert into Students (id, city, country, gender) values (329, 'Pardubice', 'Czech Republic', 'Male');
insert into Students (id, city, country, gender) values (330, 'Sigaboy', 'Philippines', 'Female');
insert into Students (id, city, country, gender) values (331, 'Jianshe', 'China', 'Female');
insert into Students (id, city, country, gender) values (332, 'Antofagasta', 'Chile', 'Male');
insert into Students (id, city, country, gender) values (333, 'La Rochelle', 'France', 'Male');
insert into Students (id, city, country, gender) values (334, 'Jishui', 'China', 'Male');
insert into Students (id, city, country, gender) values (335, 'Marantao', 'Philippines', 'Female');
insert into Students (id, city, country, gender) values (336, 'Kampen (Overijssel)', 'Netherlands', 'Male');
insert into Students (id, city, country, gender) values (337, 'Morocelí', 'Honduras', 'Female');
insert into Students (id, city, country, gender) values (338, 'Wschowa', 'Poland', 'Female');
insert into Students (id, city, country, gender) values (339, 'Téra', 'Niger', 'Male');
insert into Students (id, city, country, gender) values (340, 'Xiawa', 'China', 'Male');
insert into Students (id, city, country, gender) values (341, 'Muravlenko', 'Russia', 'Female');
insert into Students (id, city, country, gender) values (342, 'Jialou', 'China', 'Male');
insert into Students (id, city, country, gender) values (343, 'Fengshan', 'China', 'Female');
insert into Students (id, city, country, gender) values (344, 'Vostryakovo', 'Russia', 'Female');
insert into Students (id, city, country, gender) values (345, 'Kuz’minskiye Otverzhki', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (346, 'Walakeri', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (347, 'São Sebastião do Caí', 'Brazil', 'Female');
insert into Students (id, city, country, gender) values (348, 'Miki', 'Japan', 'Female');
insert into Students (id, city, country, gender) values (349, 'Xiangrong', 'China', 'Female');
insert into Students (id, city, country, gender) values (350, 'Birigui', 'Brazil', 'Male');
insert into Students (id, city, country, gender) values (351, 'Adh Dhayd', 'United Arab Emirates', 'Female');
insert into Students (id, city, country, gender) values (352, 'Bukama', 'Democratic Republic of the Congo', 'Female');
insert into Students (id, city, country, gender) values (353, 'Ushumun', 'Russia', 'Female');
insert into Students (id, city, country, gender) values (354, 'Grebnevo', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (355, 'Ulset', 'Norway', 'Male');
insert into Students (id, city, country, gender) values (356, 'Lagoa', 'Portugal', 'Male');
insert into Students (id, city, country, gender) values (357, 'Begejci', 'Serbia', 'Male');
insert into Students (id, city, country, gender) values (358, 'Legok', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (359, 'Sawahan', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (360, 'Los Dos Caminos', 'Venezuela', 'Male');
insert into Students (id, city, country, gender) values (361, 'Cibinong', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (362, 'Saverne', 'France', 'Female');
insert into Students (id, city, country, gender) values (363, 'Sergio Osmeña Sr', 'Philippines', 'Female');
insert into Students (id, city, country, gender) values (364, 'Montpellier', 'France', 'Female');
insert into Students (id, city, country, gender) values (365, 'Fentange', 'Luxembourg', 'Male');
insert into Students (id, city, country, gender) values (366, 'Suhong', 'China', 'Female');
insert into Students (id, city, country, gender) values (367, 'Sacramento', 'United States', 'Male');
insert into Students (id, city, country, gender) values (368, 'Yongfeng', 'China', 'Male');
insert into Students (id, city, country, gender) values (369, 'Radzanów', 'Poland', 'Female');
insert into Students (id, city, country, gender) values (370, 'Cabanaconde', 'Peru', 'Female');
insert into Students (id, city, country, gender) values (371, 'Stockholm', 'Sweden', 'Female');
insert into Students (id, city, country, gender) values (372, 'Xigebi', 'China', 'Male');
insert into Students (id, city, country, gender) values (373, 'Tapayan', 'Philippines', 'Female');
insert into Students (id, city, country, gender) values (374, 'København', 'Denmark', 'Female');
insert into Students (id, city, country, gender) values (375, 'Liuche', 'China', 'Female');
insert into Students (id, city, country, gender) values (376, 'Paris 10', 'France', 'Female');
insert into Students (id, city, country, gender) values (377, 'Bāqim as Sūq', 'Yemen', 'Male');
insert into Students (id, city, country, gender) values (378, 'Horokhiv', 'Ukraine', 'Male');
insert into Students (id, city, country, gender) values (379, 'Phra Nakhon Si Ayutthaya', 'Thailand', 'Male');
insert into Students (id, city, country, gender) values (380, 'Krechevitsy', 'Russia', 'Female');
insert into Students (id, city, country, gender) values (381, 'San Juan', 'Mexico', 'Female');
insert into Students (id, city, country, gender) values (382, 'Sylvan Lake', 'Canada', 'Male');
insert into Students (id, city, country, gender) values (383, 'Gasan', 'Philippines', 'Male');
insert into Students (id, city, country, gender) values (384, 'Condoroma', 'Peru', 'Female');
insert into Students (id, city, country, gender) values (385, 'Pucacaca', 'Peru', 'Female');
insert into Students (id, city, country, gender) values (386, 'Muleba', 'Tanzania', 'Male');
insert into Students (id, city, country, gender) values (387, 'Ponta Delgada', 'Portugal', 'Male');
insert into Students (id, city, country, gender) values (388, 'Zambujal', 'Portugal', 'Male');
insert into Students (id, city, country, gender) values (389, 'Sanhui', 'China', 'Male');
insert into Students (id, city, country, gender) values (390, 'Bègles', 'France', 'Male');
insert into Students (id, city, country, gender) values (391, 'Jinbi', 'China', 'Female');
insert into Students (id, city, country, gender) values (392, 'Ōtsuki', 'Japan', 'Female');
insert into Students (id, city, country, gender) values (393, 'Cilangkap', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (394, 'Pangkungparuk', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (395, 'Palhais', 'Portugal', 'Male');
insert into Students (id, city, country, gender) values (396, 'Lalukoen Dua', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (397, 'Sājūr', 'Israel', 'Female');
insert into Students (id, city, country, gender) values (398, 'Ol’gino', 'Russia', 'Female');
insert into Students (id, city, country, gender) values (399, 'Santa Cruz Cabrália', 'Brazil', 'Female');
insert into Students (id, city, country, gender) values (400, 'Shumerlya', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (401, 'Somanda', 'Tanzania', 'Male');
insert into Students (id, city, country, gender) values (402, 'Tampa', 'United States', 'Female');
insert into Students (id, city, country, gender) values (403, 'Pak Phayun', 'Thailand', 'Male');
insert into Students (id, city, country, gender) values (404, 'Horad Krychaw', 'Belarus', 'Male');
insert into Students (id, city, country, gender) values (405, 'Cartago', 'Costa Rica', 'Male');
insert into Students (id, city, country, gender) values (406, 'Marly', 'France', 'Female');
insert into Students (id, city, country, gender) values (407, 'Abreus', 'Cuba', 'Female');
insert into Students (id, city, country, gender) values (408, 'Madjeouéni', 'Comoros', 'Female');
insert into Students (id, city, country, gender) values (409, 'Vassouras', 'Brazil', 'Female');
insert into Students (id, city, country, gender) values (410, 'Chernivtsi', 'Ukraine', 'Female');
insert into Students (id, city, country, gender) values (411, 'Alvaro Obregon', 'Mexico', 'Male');
insert into Students (id, city, country, gender) values (412, 'Slobidka', 'Ukraine', 'Female');
insert into Students (id, city, country, gender) values (413, 'Yongning', 'China', 'Male');
insert into Students (id, city, country, gender) values (414, 'Rakvere', 'Estonia', 'Female');
insert into Students (id, city, country, gender) values (415, 'Mokotów', 'Poland', 'Male');
insert into Students (id, city, country, gender) values (416, 'Xinqiao', 'China', 'Female');
insert into Students (id, city, country, gender) values (417, 'Poroshkovo', 'Ukraine', 'Male');
insert into Students (id, city, country, gender) values (418, 'Luau', 'Angola', 'Female');
insert into Students (id, city, country, gender) values (419, 'Quanling', 'China', 'Female');
insert into Students (id, city, country, gender) values (420, 'Węgierska Górka', 'Poland', 'Female');
insert into Students (id, city, country, gender) values (421, 'Sarimukti Kaler', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (422, 'Roche-à-Bateau', 'Haiti', 'Female');
insert into Students (id, city, country, gender) values (423, 'Guishan', 'China', 'Female');
insert into Students (id, city, country, gender) values (424, 'Zābolī', 'Iran', 'Male');
insert into Students (id, city, country, gender) values (425, 'Gabahan', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (426, 'La Loma', 'Mexico', 'Male');
insert into Students (id, city, country, gender) values (427, 'Piraju', 'Brazil', 'Female');
insert into Students (id, city, country, gender) values (428, 'Urrô', 'Portugal', 'Female');
insert into Students (id, city, country, gender) values (429, 'Pianbai', 'China', 'Male');
insert into Students (id, city, country, gender) values (430, 'Ādam', 'Oman', 'Male');
insert into Students (id, city, country, gender) values (431, 'Los Boquerones', 'Panama', 'Female');
insert into Students (id, city, country, gender) values (432, 'Libas', 'Philippines', 'Male');
insert into Students (id, city, country, gender) values (433, 'Kilim', 'Philippines', 'Female');
insert into Students (id, city, country, gender) values (434, 'Tafeng', 'China', 'Female');
insert into Students (id, city, country, gender) values (435, 'Suwon-si', 'South Korea', 'Female');
insert into Students (id, city, country, gender) values (436, 'Novo-Peredelkino', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (437, 'Qa‘ţabah', 'Yemen', 'Male');
insert into Students (id, city, country, gender) values (438, 'Atsugi', 'Japan', 'Female');
insert into Students (id, city, country, gender) values (439, 'Karmah an Nuzul', 'Sudan', 'Female');
insert into Students (id, city, country, gender) values (440, 'Zlaté Hory', 'Czech Republic', 'Female');
insert into Students (id, city, country, gender) values (441, 'Itacurubí del Rosario', 'Paraguay', 'Female');
insert into Students (id, city, country, gender) values (442, 'Maracaju', 'Brazil', 'Male');
insert into Students (id, city, country, gender) values (443, 'Erba', 'China', 'Female');
insert into Students (id, city, country, gender) values (444, 'San Antonio', 'United States', 'Female');
insert into Students (id, city, country, gender) values (445, 'Úštěk', 'Czech Republic', 'Male');
insert into Students (id, city, country, gender) values (446, 'Fengtang', 'China', 'Male');
insert into Students (id, city, country, gender) values (447, 'Miharu', 'Japan', 'Female');
insert into Students (id, city, country, gender) values (448, 'Liulihe', 'China', 'Male');
insert into Students (id, city, country, gender) values (449, 'Cikupa', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (450, 'Sutton', 'United Kingdom', 'Female');
insert into Students (id, city, country, gender) values (451, 'Luyang', 'China', 'Male');
insert into Students (id, city, country, gender) values (452, 'Zaoxi', 'China', 'Male');
insert into Students (id, city, country, gender) values (453, 'København', 'Denmark', 'Male');
insert into Students (id, city, country, gender) values (454, 'Huixing', 'China', 'Male');
insert into Students (id, city, country, gender) values (455, 'Jiahe', 'China', 'Male');
insert into Students (id, city, country, gender) values (456, 'Cuchumbaya', 'Peru', 'Female');
insert into Students (id, city, country, gender) values (457, 'Mazowe', 'Zimbabwe', 'Female');
insert into Students (id, city, country, gender) values (458, 'Linjiang', 'China', 'Female');
insert into Students (id, city, country, gender) values (459, 'Abrantes', 'Portugal', 'Male');
insert into Students (id, city, country, gender) values (460, 'Concórdia', 'Brazil', 'Male');
insert into Students (id, city, country, gender) values (461, 'Olympia', 'United States', 'Female');
insert into Students (id, city, country, gender) values (462, 'Pudoc North', 'Philippines', 'Male');
insert into Students (id, city, country, gender) values (463, 'Yelan’', 'Russia', 'Female');
insert into Students (id, city, country, gender) values (464, 'Xiadian', 'China', 'Male');
insert into Students (id, city, country, gender) values (465, 'Bandungsari', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (466, 'Beigou', 'China', 'Female');
insert into Students (id, city, country, gender) values (467, 'Uddevalla', 'Sweden', 'Female');
insert into Students (id, city, country, gender) values (468, 'Fukuchiyama', 'Japan', 'Female');
insert into Students (id, city, country, gender) values (469, 'Wangfu', 'China', 'Female');
insert into Students (id, city, country, gender) values (470, 'Butuan', 'Philippines', 'Male');
insert into Students (id, city, country, gender) values (471, 'Krasnogorskiy', 'Russia', 'Female');
insert into Students (id, city, country, gender) values (472, 'Zavidovo', 'Russia', 'Female');
insert into Students (id, city, country, gender) values (473, 'Samut Songkhram', 'Thailand', 'Female');
insert into Students (id, city, country, gender) values (474, 'Hamada', 'Japan', 'Female');
insert into Students (id, city, country, gender) values (475, 'Haoba', 'China', 'Male');
insert into Students (id, city, country, gender) values (476, 'Maicao', 'Colombia', 'Female');
insert into Students (id, city, country, gender) values (477, 'Maiyema', 'Nigeria', 'Female');
insert into Students (id, city, country, gender) values (478, 'Sedlčany', 'Czech Republic', 'Male');
insert into Students (id, city, country, gender) values (479, 'Kulautuva', 'Lithuania', 'Male');
insert into Students (id, city, country, gender) values (480, 'Baiguo', 'China', 'Male');
insert into Students (id, city, country, gender) values (481, 'Uren’', 'Russia', 'Female');
insert into Students (id, city, country, gender) values (482, 'Vaiusu', 'Samoa', 'Male');
insert into Students (id, city, country, gender) values (483, 'Mabusag', 'Philippines', 'Female');
insert into Students (id, city, country, gender) values (484, 'Natitingou', 'Benin', 'Male');
insert into Students (id, city, country, gender) values (485, 'Lunao', 'Philippines', 'Male');
insert into Students (id, city, country, gender) values (486, 'Khanabad', 'Afghanistan', 'Female');
insert into Students (id, city, country, gender) values (487, 'Cartí Suitupo', 'Panama', 'Male');
insert into Students (id, city, country, gender) values (488, 'Suure-Jaani', 'Estonia', 'Male');
insert into Students (id, city, country, gender) values (489, 'Kurayoshi', 'Japan', 'Male');
insert into Students (id, city, country, gender) values (490, 'Tahara', 'Japan', 'Female');
insert into Students (id, city, country, gender) values (491, 'Menlou’ao', 'China', 'Male');
insert into Students (id, city, country, gender) values (492, 'Helmsange', 'Luxembourg', 'Male');
insert into Students (id, city, country, gender) values (493, 'Jega', 'Nigeria', 'Male');
insert into Students (id, city, country, gender) values (494, 'Sa‘sa‘', 'Syria', 'Female');
insert into Students (id, city, country, gender) values (495, 'Mjamaoué', 'Comoros', 'Male');
insert into Students (id, city, country, gender) values (496, 'Ribas', 'Portugal', 'Female');
insert into Students (id, city, country, gender) values (497, 'Kyonju', 'South Korea', 'Male');
insert into Students (id, city, country, gender) values (498, 'Fenghuo', 'China', 'Female');
insert into Students (id, city, country, gender) values (499, 'Masatepe', 'Nicaragua', 'Female');
insert into Students (id, city, country, gender) values (500, 'Qulai', 'China', 'Male');
insert into Students (id, city, country, gender) values (501, 'Beo', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (502, 'Velizh', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (503, 'Laslovo', 'Croatia', 'Male');
insert into Students (id, city, country, gender) values (504, 'Pacaraos', 'Peru', 'Female');
insert into Students (id, city, country, gender) values (505, 'Ke’erlun', 'China', 'Female');
insert into Students (id, city, country, gender) values (506, 'Xianghu', 'China', 'Male');
insert into Students (id, city, country, gender) values (507, 'Batticaloa', 'Sri Lanka', 'Male');
insert into Students (id, city, country, gender) values (508, 'Kiernozia', 'Poland', 'Female');
insert into Students (id, city, country, gender) values (509, 'Al Maḩallah al Kubrá', 'Egypt', 'Female');
insert into Students (id, city, country, gender) values (510, 'Długosiodło', 'Poland', 'Female');
insert into Students (id, city, country, gender) values (511, 'Coruripe', 'Brazil', 'Female');
insert into Students (id, city, country, gender) values (512, 'Yuxi', 'China', 'Male');
insert into Students (id, city, country, gender) values (513, 'Dahe', 'China', 'Male');
insert into Students (id, city, country, gender) values (514, 'Kawaliwu', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (515, 'Pushkino', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (516, 'Maru', 'Nigeria', 'Male');
insert into Students (id, city, country, gender) values (517, 'Ermida', 'Portugal', 'Female');
insert into Students (id, city, country, gender) values (518, 'São João do Campo', 'Portugal', 'Male');
insert into Students (id, city, country, gender) values (519, 'Ipoh', 'Malaysia', 'Male');
insert into Students (id, city, country, gender) values (520, 'Sangallaya', 'Peru', 'Female');
insert into Students (id, city, country, gender) values (521, 'Norrköping', 'Sweden', 'Female');
insert into Students (id, city, country, gender) values (522, 'Huilongshan', 'China', 'Female');
insert into Students (id, city, country, gender) values (523, 'San Agustín', 'El Salvador', 'Female');
insert into Students (id, city, country, gender) values (524, 'Psebay', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (525, 'Zhapu', 'China', 'Male');
insert into Students (id, city, country, gender) values (526, 'Ar Rawḑ', 'Yemen', 'Male');
insert into Students (id, city, country, gender) values (527, 'Melaka', 'Malaysia', 'Female');
insert into Students (id, city, country, gender) values (528, 'Hearst', 'Canada', 'Female');
insert into Students (id, city, country, gender) values (529, 'Borgarnes', 'Iceland', 'Male');
insert into Students (id, city, country, gender) values (530, 'Siao', 'Thailand', 'Male');
insert into Students (id, city, country, gender) values (531, 'Capiíbary', 'Paraguay', 'Female');
insert into Students (id, city, country, gender) values (532, 'San José', 'Costa Rica', 'Female');
insert into Students (id, city, country, gender) values (533, 'Hongyan', 'China', 'Female');
insert into Students (id, city, country, gender) values (534, 'Taltal', 'Chile', 'Male');
insert into Students (id, city, country, gender) values (535, 'Marseille', 'France', 'Female');
insert into Students (id, city, country, gender) values (536, 'El Regalo', 'Venezuela', 'Female');
insert into Students (id, city, country, gender) values (537, 'Cibunar', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (538, 'La Salud', 'Cuba', 'Female');
insert into Students (id, city, country, gender) values (539, 'Trail', 'Canada', 'Female');
insert into Students (id, city, country, gender) values (540, 'Rizal', 'Philippines', 'Male');
insert into Students (id, city, country, gender) values (541, 'Morangis', 'France', 'Female');
insert into Students (id, city, country, gender) values (542, 'Chãos', 'Portugal', 'Female');
insert into Students (id, city, country, gender) values (543, 'Datartua', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (544, 'Al Manzilah', 'Egypt', 'Male');
insert into Students (id, city, country, gender) values (545, 'Akron', 'United States', 'Male');
insert into Students (id, city, country, gender) values (546, 'Deneysville', 'South Africa', 'Male');
insert into Students (id, city, country, gender) values (547, 'Qiancang', 'China', 'Male');
insert into Students (id, city, country, gender) values (548, 'Montevista', 'Philippines', 'Female');
insert into Students (id, city, country, gender) values (549, 'Vagonoremont', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (550, 'Marechal Cândido Rondon', 'Brazil', 'Female');
insert into Students (id, city, country, gender) values (551, 'Karonga', 'Malawi', 'Female');
insert into Students (id, city, country, gender) values (552, 'Novyye Kuz’minki', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (553, 'Tworków', 'Poland', 'Male');
insert into Students (id, city, country, gender) values (554, 'Trudobelikovskiy', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (555, 'Kastrat', 'Albania', 'Male');
insert into Students (id, city, country, gender) values (556, 'Gamleby', 'Sweden', 'Male');
insert into Students (id, city, country, gender) values (557, 'Rio Covo', 'Portugal', 'Male');
insert into Students (id, city, country, gender) values (558, 'Vrbovec', 'Croatia', 'Male');
insert into Students (id, city, country, gender) values (559, 'Syrostan', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (560, 'Shangxing', 'China', 'Female');
insert into Students (id, city, country, gender) values (561, 'Huayllo', 'Peru', 'Male');
insert into Students (id, city, country, gender) values (562, 'Oslo', 'Norway', 'Male');
insert into Students (id, city, country, gender) values (563, 'Claveria', 'Philippines', 'Male');
insert into Students (id, city, country, gender) values (564, 'Sala', 'Latvia', 'Male');
insert into Students (id, city, country, gender) values (565, 'Bogotá', 'Colombia', 'Male');
insert into Students (id, city, country, gender) values (566, 'Parung', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (567, 'Örnsköldsvik', 'Sweden', 'Female');
insert into Students (id, city, country, gender) values (568, 'Titao', 'Burkina Faso', 'Female');
insert into Students (id, city, country, gender) values (569, 'Yong’an', 'China', 'Male');
insert into Students (id, city, country, gender) values (570, 'João Câmara', 'Brazil', 'Female');
insert into Students (id, city, country, gender) values (571, 'Mafa', 'Nigeria', 'Female');
insert into Students (id, city, country, gender) values (572, 'Santiago de Subrrifana', 'Portugal', 'Male');
insert into Students (id, city, country, gender) values (573, 'Dahe', 'China', 'Female');
insert into Students (id, city, country, gender) values (574, 'Tagana-an', 'Philippines', 'Male');
insert into Students (id, city, country, gender) values (575, 'Aveleda', 'Portugal', 'Female');
insert into Students (id, city, country, gender) values (576, 'Huancheng', 'China', 'Male');
insert into Students (id, city, country, gender) values (577, 'Arroyo Naranjo', 'Cuba', 'Male');
insert into Students (id, city, country, gender) values (578, 'Villarrica', 'Chile', 'Female');
insert into Students (id, city, country, gender) values (579, 'Rusnė', 'Lithuania', 'Female');
insert into Students (id, city, country, gender) values (580, 'Helsingborg', 'Sweden', 'Male');
insert into Students (id, city, country, gender) values (581, 'Azogues', 'Ecuador', 'Female');
insert into Students (id, city, country, gender) values (582, 'Pondokwungu', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (583, 'Faeanak Dua', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (584, 'Niechanowo', 'Poland', 'Female');
insert into Students (id, city, country, gender) values (585, 'Wanmao', 'China', 'Male');
insert into Students (id, city, country, gender) values (586, 'Vol’nyy Aul', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (587, 'Tiancheng', 'China', 'Male');
insert into Students (id, city, country, gender) values (588, 'Acolla', 'Peru', 'Male');
insert into Students (id, city, country, gender) values (589, 'Somorpenang', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (590, 'Kaolinovo', 'Bulgaria', 'Male');
insert into Students (id, city, country, gender) values (591, 'Ystad', 'Sweden', 'Female');
insert into Students (id, city, country, gender) values (592, 'Itajubá', 'Brazil', 'Female');
insert into Students (id, city, country, gender) values (593, 'Lyon', 'France', 'Male');
insert into Students (id, city, country, gender) values (594, 'Longsheng', 'China', 'Female');
insert into Students (id, city, country, gender) values (595, 'Wuxiang', 'China', 'Female');
insert into Students (id, city, country, gender) values (596, 'Capioví', 'Argentina', 'Male');
insert into Students (id, city, country, gender) values (597, 'San Eugenio', 'Philippines', 'Male');
insert into Students (id, city, country, gender) values (598, 'Balky', 'Ukraine', 'Female');
insert into Students (id, city, country, gender) values (599, 'Rejoagung', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (600, 'Palauig', 'Philippines', 'Male');
insert into Students (id, city, country, gender) values (601, 'Charlottetown', 'Canada', 'Female');
insert into Students (id, city, country, gender) values (602, 'Kawit', 'Philippines', 'Female');
insert into Students (id, city, country, gender) values (603, 'Borek', 'Poland', 'Female');
insert into Students (id, city, country, gender) values (604, 'Andou', 'China', 'Male');
insert into Students (id, city, country, gender) values (605, 'Saltsjö-Boo', 'Sweden', 'Male');
insert into Students (id, city, country, gender) values (606, 'Akkol’', 'Kazakhstan', 'Female');
insert into Students (id, city, country, gender) values (607, 'Santa Rosa de Cabal', 'Colombia', 'Male');
insert into Students (id, city, country, gender) values (608, 'Laszki', 'Poland', 'Male');
insert into Students (id, city, country, gender) values (609, 'Zhongzhou', 'China', 'Female');
insert into Students (id, city, country, gender) values (610, 'Rayevskiy', 'Russia', 'Female');
insert into Students (id, city, country, gender) values (611, 'Manoc-Manoc', 'Philippines', 'Female');
insert into Students (id, city, country, gender) values (612, 'Jiaoqi', 'China', 'Male');
insert into Students (id, city, country, gender) values (613, 'Nekhayevskiy', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (614, 'Cerro Colorado', 'Uruguay', 'Female');
insert into Students (id, city, country, gender) values (615, 'Prado', 'Colombia', 'Male');
insert into Students (id, city, country, gender) values (616, 'Valença', 'Brazil', 'Female');
insert into Students (id, city, country, gender) values (617, 'Yaxi', 'China', 'Female');
insert into Students (id, city, country, gender) values (618, 'Busan', 'South Korea', 'Female');
insert into Students (id, city, country, gender) values (619, 'Apurawan', 'Philippines', 'Male');
insert into Students (id, city, country, gender) values (620, 'Daitōchō', 'Japan', 'Female');
insert into Students (id, city, country, gender) values (621, 'Seixezelo', 'Portugal', 'Male');
insert into Students (id, city, country, gender) values (622, 'Ciudad Barrios', 'El Salvador', 'Male');
insert into Students (id, city, country, gender) values (623, 'Jiaomingsi', 'China', 'Male');
insert into Students (id, city, country, gender) values (624, 'Chelles', 'France', 'Male');
insert into Students (id, city, country, gender) values (625, 'Zaragoza', 'Mexico', 'Male');
insert into Students (id, city, country, gender) values (626, 'Yuanmou', 'China', 'Male');
insert into Students (id, city, country, gender) values (627, 'Taesal-li', 'South Korea', 'Male');
insert into Students (id, city, country, gender) values (628, 'Mūḩ Ḩasan', 'Syria', 'Male');
insert into Students (id, city, country, gender) values (629, 'Kostryzhivka', 'Ukraine', 'Male');
insert into Students (id, city, country, gender) values (630, 'Fort Wayne', 'United States', 'Male');
insert into Students (id, city, country, gender) values (631, 'Cisasak', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (632, 'Palaiochóri', 'Greece', 'Male');
insert into Students (id, city, country, gender) values (633, 'Jargalant', 'Mongolia', 'Male');
insert into Students (id, city, country, gender) values (634, 'Pamatang', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (635, 'Sukmoilang', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (636, 'Rasskazovo', 'Russia', 'Female');
insert into Students (id, city, country, gender) values (637, 'Beltinci', 'Slovenia', 'Male');
insert into Students (id, city, country, gender) values (638, 'Dukuh Kaler', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (639, 'Pochinki', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (640, 'El Águila', 'Colombia', 'Female');
insert into Students (id, city, country, gender) values (641, 'Guanli', 'China', 'Female');
insert into Students (id, city, country, gender) values (642, 'Montepuez', 'Mozambique', 'Male');
insert into Students (id, city, country, gender) values (643, 'Myski', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (644, 'Zouérat', 'Mauritania', 'Male');
insert into Students (id, city, country, gender) values (645, 'Queluz', 'Portugal', 'Male');
insert into Students (id, city, country, gender) values (646, 'Tongshan', 'China', 'Female');
insert into Students (id, city, country, gender) values (647, 'Gongfang', 'China', 'Female');
insert into Students (id, city, country, gender) values (648, 'Santyoku', 'South Korea', 'Female');
insert into Students (id, city, country, gender) values (649, 'Quinuabamba', 'Peru', 'Female');
insert into Students (id, city, country, gender) values (650, 'Palguyod', 'Philippines', 'Female');
insert into Students (id, city, country, gender) values (651, 'Mungging', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (652, 'Lubień Kujawski', 'Poland', 'Female');
insert into Students (id, city, country, gender) values (653, 'Copa', 'Peru', 'Male');
insert into Students (id, city, country, gender) values (654, 'Porto Real', 'Brazil', 'Male');
insert into Students (id, city, country, gender) values (655, 'Arcueil', 'France', 'Female');
insert into Students (id, city, country, gender) values (656, 'Uvarovka', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (657, 'Beiqi', 'China', 'Female');
insert into Students (id, city, country, gender) values (658, 'Nancy', 'France', 'Male');
insert into Students (id, city, country, gender) values (659, 'Kirtipur', 'Nepal', 'Female');
insert into Students (id, city, country, gender) values (660, 'Pereleshino', 'Russia', 'Female');
insert into Students (id, city, country, gender) values (661, 'Alegria', 'Philippines', 'Male');
insert into Students (id, city, country, gender) values (662, 'Yumbo', 'Colombia', 'Female');
insert into Students (id, city, country, gender) values (663, 'Maslovka', 'Russia', 'Female');
insert into Students (id, city, country, gender) values (664, 'Ranchuelo', 'Cuba', 'Female');
insert into Students (id, city, country, gender) values (665, 'Mogi Guaçu', 'Brazil', 'Male');
insert into Students (id, city, country, gender) values (666, 'Hirosaki', 'Japan', 'Male');
insert into Students (id, city, country, gender) values (667, 'Krzemieniewo', 'Poland', 'Female');
insert into Students (id, city, country, gender) values (668, 'Cuilco', 'Guatemala', 'Female');
insert into Students (id, city, country, gender) values (669, 'Valencia', 'Venezuela', 'Female');
insert into Students (id, city, country, gender) values (670, 'Plei Kần', 'Vietnam', 'Male');
insert into Students (id, city, country, gender) values (671, 'Kosum Phisai', 'Thailand', 'Male');
insert into Students (id, city, country, gender) values (672, 'Rancharia', 'Brazil', 'Female');
insert into Students (id, city, country, gender) values (673, 'Potosí', 'Bolivia', 'Male');
insert into Students (id, city, country, gender) values (674, 'Poshekhon’ye', 'Russia', 'Female');
insert into Students (id, city, country, gender) values (675, 'Cotaparaco', 'Peru', 'Male');
insert into Students (id, city, country, gender) values (676, 'Sokoto', 'Nigeria', 'Male');
insert into Students (id, city, country, gender) values (677, 'Emiliano Zapata', 'Mexico', 'Male');
insert into Students (id, city, country, gender) values (678, 'Portland', 'United States', 'Male');
insert into Students (id, city, country, gender) values (679, 'Talcahuano', 'Chile', 'Male');
insert into Students (id, city, country, gender) values (680, 'Kameyama', 'Japan', 'Female');
insert into Students (id, city, country, gender) values (681, 'Oslo', 'Norway', 'Female');
insert into Students (id, city, country, gender) values (682, 'Mórrope', 'Peru', 'Male');
insert into Students (id, city, country, gender) values (683, 'Riangderi', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (684, 'Las Animas', 'Mexico', 'Female');
insert into Students (id, city, country, gender) values (685, 'Khlong Sam Wa', 'Thailand', 'Female');
insert into Students (id, city, country, gender) values (686, 'Hacienda La Calera', 'Chile', 'Male');
insert into Students (id, city, country, gender) values (687, 'Aleg', 'Mauritania', 'Female');
insert into Students (id, city, country, gender) values (688, 'Yanghong', 'China', 'Female');
insert into Students (id, city, country, gender) values (689, 'Storozhnytsya', 'Ukraine', 'Male');
insert into Students (id, city, country, gender) values (690, 'Daduo', 'China', 'Male');
insert into Students (id, city, country, gender) values (691, 'Lubao', 'Philippines', 'Female');
insert into Students (id, city, country, gender) values (692, 'Duwakbuter', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (693, 'Campo Verde', 'Brazil', 'Female');
insert into Students (id, city, country, gender) values (694, 'Kangmei', 'China', 'Female');
insert into Students (id, city, country, gender) values (695, 'Novoselë', 'Albania', 'Male');
insert into Students (id, city, country, gender) values (696, 'Memphis', 'United States', 'Female');
insert into Students (id, city, country, gender) values (697, 'Kuybyshevskiy Zaton', 'Russia', 'Female');
insert into Students (id, city, country, gender) values (698, 'Jacaraú', 'Brazil', 'Male');
insert into Students (id, city, country, gender) values (699, 'Fonte da Aldeia', 'Portugal', 'Male');
insert into Students (id, city, country, gender) values (700, 'Wufeng', 'China', 'Female');
insert into Students (id, city, country, gender) values (701, 'Merkezköy', 'Turkey', 'Male');
insert into Students (id, city, country, gender) values (702, 'Rongmei', 'China', 'Female');
insert into Students (id, city, country, gender) values (703, 'Rashaant', 'Mongolia', 'Male');
insert into Students (id, city, country, gender) values (704, 'Shimen', 'China', 'Female');
insert into Students (id, city, country, gender) values (705, 'Nueva Requena', 'Peru', 'Male');
insert into Students (id, city, country, gender) values (706, 'Pombal', 'Portugal', 'Male');
insert into Students (id, city, country, gender) values (707, 'Gobernador Costa', 'Argentina', 'Female');
insert into Students (id, city, country, gender) values (708, 'Effium', 'Nigeria', 'Female');
insert into Students (id, city, country, gender) values (709, 'Shanghe', 'China', 'Female');
insert into Students (id, city, country, gender) values (710, 'Tanjungpecinan Utara', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (711, 'Sano', 'Japan', 'Male');
insert into Students (id, city, country, gender) values (712, 'Usa River', 'Tanzania', 'Female');
insert into Students (id, city, country, gender) values (713, 'Linares', 'Chile', 'Female');
insert into Students (id, city, country, gender) values (714, 'Jambubol', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (715, 'Nabire', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (716, 'Quiruvilca', 'Peru', 'Female');
insert into Students (id, city, country, gender) values (717, 'Salimbalan', 'Philippines', 'Male');
insert into Students (id, city, country, gender) values (718, 'Zhaoxiang', 'China', 'Female');
insert into Students (id, city, country, gender) values (719, 'Plato', 'Colombia', 'Male');
insert into Students (id, city, country, gender) values (720, 'Nierumai', 'China', 'Male');
insert into Students (id, city, country, gender) values (721, 'Pilang', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (722, 'Shūkat aş Şūfī', 'Palestinian Territory', 'Female');
insert into Students (id, city, country, gender) values (723, 'Bom Sucesso', 'Portugal', 'Male');
insert into Students (id, city, country, gender) values (724, 'Shangshaleng', 'China', 'Male');
insert into Students (id, city, country, gender) values (725, 'Česká Skalice', 'Czech Republic', 'Female');
insert into Students (id, city, country, gender) values (726, 'Jati', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (727, 'Kristinestad', 'Finland', 'Female');
insert into Students (id, city, country, gender) values (728, 'Syanno', 'Belarus', 'Female');
insert into Students (id, city, country, gender) values (729, 'Torrance', 'United States', 'Female');
insert into Students (id, city, country, gender) values (730, 'Huhe', 'China', 'Female');
insert into Students (id, city, country, gender) values (731, 'Balkh', 'Afghanistan', 'Female');
insert into Students (id, city, country, gender) values (732, 'Hanyuan', 'China', 'Female');
insert into Students (id, city, country, gender) values (733, 'Palaran', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (734, 'Passos', 'Portugal', 'Female');
insert into Students (id, city, country, gender) values (735, 'Tuodian', 'China', 'Male');
insert into Students (id, city, country, gender) values (736, 'Forestville', 'Canada', 'Female');
insert into Students (id, city, country, gender) values (737, 'Píritu', 'Venezuela', 'Female');
insert into Students (id, city, country, gender) values (738, 'Xiaxihao', 'China', 'Female');
insert into Students (id, city, country, gender) values (739, 'Doujia', 'China', 'Female');
insert into Students (id, city, country, gender) values (740, 'Dueñas', 'Philippines', 'Female');
insert into Students (id, city, country, gender) values (741, 'Rozhniv', 'Ukraine', 'Female');
insert into Students (id, city, country, gender) values (742, 'San Pedro', 'Belize', 'Female');
insert into Students (id, city, country, gender) values (743, 'Yanglin', 'China', 'Male');
insert into Students (id, city, country, gender) values (744, 'Lyalichi', 'Russia', 'Female');
insert into Students (id, city, country, gender) values (745, 'Piraquara', 'Brazil', 'Male');
insert into Students (id, city, country, gender) values (746, 'Mempawah', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (747, 'Dangcalan', 'Philippines', 'Female');
insert into Students (id, city, country, gender) values (748, 'Anseong', 'South Korea', 'Male');
insert into Students (id, city, country, gender) values (749, 'La Unión', 'Peru', 'Female');
insert into Students (id, city, country, gender) values (750, 'la Massana', 'Andorra', 'Male');
insert into Students (id, city, country, gender) values (751, 'Jinjiang', 'China', 'Male');
insert into Students (id, city, country, gender) values (752, 'Carbajales', 'Honduras', 'Male');
insert into Students (id, city, country, gender) values (753, 'Karajeun', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (754, 'Parigi', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (755, 'Daykitin', 'Philippines', 'Female');
insert into Students (id, city, country, gender) values (756, 'San Juan Bautista', 'Venezuela', 'Female');
insert into Students (id, city, country, gender) values (757, 'Kristiansand S', 'Norway', 'Male');
insert into Students (id, city, country, gender) values (758, 'Kanthararom', 'Thailand', 'Female');
insert into Students (id, city, country, gender) values (759, 'Yingdianjie', 'China', 'Male');
insert into Students (id, city, country, gender) values (760, 'Antwerpen', 'Belgium', 'Male');
insert into Students (id, city, country, gender) values (761, 'Guiset East', 'Philippines', 'Female');
insert into Students (id, city, country, gender) values (762, 'Teutônia', 'Brazil', 'Female');
insert into Students (id, city, country, gender) values (763, 'Ketapang', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (764, 'Kiryandongo', 'Uganda', 'Female');
insert into Students (id, city, country, gender) values (765, 'Lumijoki', 'Finland', 'Male');
insert into Students (id, city, country, gender) values (766, 'Huyuan', 'China', 'Male');
insert into Students (id, city, country, gender) values (767, 'Si Narong', 'Thailand', 'Female');
insert into Students (id, city, country, gender) values (768, 'Tabug', 'Philippines', 'Male');
insert into Students (id, city, country, gender) values (769, 'Novo Hamburgo', 'Brazil', 'Female');
insert into Students (id, city, country, gender) values (770, 'Dongkengkou', 'China', 'Male');
insert into Students (id, city, country, gender) values (771, 'Pidvolochys’k', 'Ukraine', 'Female');
insert into Students (id, city, country, gender) values (772, 'Shangfang', 'China', 'Female');
insert into Students (id, city, country, gender) values (773, 'Malino', 'Philippines', 'Male');
insert into Students (id, city, country, gender) values (774, 'Dajie', 'China', 'Female');
insert into Students (id, city, country, gender) values (775, 'Shichuan', 'China', 'Male');
insert into Students (id, city, country, gender) values (776, 'Mukhen', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (777, 'Nanying', 'China', 'Female');
insert into Students (id, city, country, gender) values (778, 'Compiègne', 'France', 'Female');
insert into Students (id, city, country, gender) values (779, 'Youxikou', 'China', 'Male');
insert into Students (id, city, country, gender) values (780, 'Jasieniec', 'Poland', 'Female');
insert into Students (id, city, country, gender) values (781, 'Itiruçu', 'Brazil', 'Female');
insert into Students (id, city, country, gender) values (782, 'Ténenkou', 'Mali', 'Male');
insert into Students (id, city, country, gender) values (783, 'Maradi', 'Niger', 'Female');
insert into Students (id, city, country, gender) values (784, 'Pelym', 'Russia', 'Female');
insert into Students (id, city, country, gender) values (785, 'Podolí', 'Czech Republic', 'Male');
insert into Students (id, city, country, gender) values (786, 'Radiměř', 'Czech Republic', 'Female');
insert into Students (id, city, country, gender) values (787, 'Pilpichaca', 'Peru', 'Female');
insert into Students (id, city, country, gender) values (788, 'Hele', 'China', 'Male');
insert into Students (id, city, country, gender) values (789, 'Gopaan', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (790, 'Santana do Ipanema', 'Brazil', 'Female');
insert into Students (id, city, country, gender) values (791, 'Piła', 'Poland', 'Female');
insert into Students (id, city, country, gender) values (792, 'Hubynykha', 'Ukraine', 'Male');
insert into Students (id, city, country, gender) values (793, 'Calumpit', 'Philippines', 'Male');
insert into Students (id, city, country, gender) values (794, 'Pensacola', 'United States', 'Male');
insert into Students (id, city, country, gender) values (795, 'Bystřice nad Pernštejnem', 'Czech Republic', 'Male');
insert into Students (id, city, country, gender) values (796, 'Borek', 'Poland', 'Female');
insert into Students (id, city, country, gender) values (797, 'Dongguang', 'China', 'Male');
insert into Students (id, city, country, gender) values (798, 'Mönchengladbach', 'Germany', 'Male');
insert into Students (id, city, country, gender) values (799, 'Heqing', 'China', 'Male');
insert into Students (id, city, country, gender) values (800, 'Novoye Leushino', 'Russia', 'Female');
insert into Students (id, city, country, gender) values (801, 'Nybro', 'Sweden', 'Male');
insert into Students (id, city, country, gender) values (802, 'Bīleh Savār', 'Iran', 'Male');
insert into Students (id, city, country, gender) values (803, 'Arendal', 'Norway', 'Male');
insert into Students (id, city, country, gender) values (804, 'Kolobovo', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (805, 'Bayawan', 'Philippines', 'Male');
insert into Students (id, city, country, gender) values (806, 'Aksu', 'Kazakhstan', 'Female');
insert into Students (id, city, country, gender) values (807, 'Selydove', 'Ukraine', 'Male');
insert into Students (id, city, country, gender) values (808, 'Tiên Lãng', 'Vietnam', 'Female');
insert into Students (id, city, country, gender) values (809, 'Labnig', 'Philippines', 'Female');
insert into Students (id, city, country, gender) values (810, 'Yangying', 'China', 'Male');
insert into Students (id, city, country, gender) values (811, 'Pelym', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (812, 'San Vicente', 'Costa Rica', 'Male');
insert into Students (id, city, country, gender) values (813, 'Angers', 'France', 'Female');
insert into Students (id, city, country, gender) values (814, 'São Sebastião do Caí', 'Brazil', 'Male');
insert into Students (id, city, country, gender) values (815, 'Várzea', 'Portugal', 'Female');
insert into Students (id, city, country, gender) values (816, 'Ancol', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (817, 'Khiwa', 'Uzbekistan', 'Female');
insert into Students (id, city, country, gender) values (818, 'Nenotes', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (819, 'Coelho Neto', 'Brazil', 'Male');
insert into Students (id, city, country, gender) values (820, 'Xianju', 'China', 'Female');
insert into Students (id, city, country, gender) values (821, 'Birr', 'Ireland', 'Female');
insert into Students (id, city, country, gender) values (822, 'Kalloní', 'Greece', 'Male');
insert into Students (id, city, country, gender) values (823, 'Kardítsa', 'Greece', 'Male');
insert into Students (id, city, country, gender) values (824, 'Siteía', 'Greece', 'Female');
insert into Students (id, city, country, gender) values (825, 'Liuhao', 'China', 'Female');
insert into Students (id, city, country, gender) values (826, 'Colmar', 'France', 'Female');
insert into Students (id, city, country, gender) values (827, 'Betulia', 'Colombia', 'Female');
insert into Students (id, city, country, gender) values (828, 'Kerbuyan', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (829, 'Amolatar', 'Uganda', 'Female');
insert into Students (id, city, country, gender) values (830, 'José Bonifácio', 'Brazil', 'Male');
insert into Students (id, city, country, gender) values (831, 'Blachownia', 'Poland', 'Female');
insert into Students (id, city, country, gender) values (832, 'Santiago De Compostela', 'Spain', 'Male');
insert into Students (id, city, country, gender) values (833, 'Panevėžys', 'Lithuania', 'Male');
insert into Students (id, city, country, gender) values (834, 'Kontagora', 'Nigeria', 'Female');
insert into Students (id, city, country, gender) values (835, 'Vista Hermosa', 'Mexico', 'Male');
insert into Students (id, city, country, gender) values (836, 'Infonavit', 'Mexico', 'Female');
insert into Students (id, city, country, gender) values (837, 'Izumi', 'Japan', 'Male');
insert into Students (id, city, country, gender) values (838, 'Ciudian', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (839, 'Niaojin', 'China', 'Female');
insert into Students (id, city, country, gender) values (840, 'Parion', 'Philippines', 'Male');
insert into Students (id, city, country, gender) values (841, 'Baru', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (842, 'Bitaogan', 'Philippines', 'Female');
insert into Students (id, city, country, gender) values (843, 'Dongping', 'China', 'Male');
insert into Students (id, city, country, gender) values (844, 'Sezimovo Ústí', 'Czech Republic', 'Female');
insert into Students (id, city, country, gender) values (845, 'Nesovice', 'Czech Republic', 'Male');
insert into Students (id, city, country, gender) values (846, 'Milíkov', 'Czech Republic', 'Female');
insert into Students (id, city, country, gender) values (847, 'Dingjiaqiao', 'China', 'Male');
insert into Students (id, city, country, gender) values (848, 'Grudë-Fushë', 'Albania', 'Female');
insert into Students (id, city, country, gender) values (849, 'Sungailiat', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (850, 'Shanhe', 'China', 'Female');
insert into Students (id, city, country, gender) values (851, 'Isakly', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (852, 'Skövde', 'Sweden', 'Male');
insert into Students (id, city, country, gender) values (853, 'Boise', 'United States', 'Female');
insert into Students (id, city, country, gender) values (854, 'Callao', 'Peru', 'Male');
insert into Students (id, city, country, gender) values (855, 'Volksrust', 'South Africa', 'Male');
insert into Students (id, city, country, gender) values (856, 'Lolak', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (857, 'Orenburg', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (858, 'Cimara', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (859, 'Jiubao', 'China', 'Female');
insert into Students (id, city, country, gender) values (860, 'Hetian', 'China', 'Female');
insert into Students (id, city, country, gender) values (861, 'Gines-Patay', 'Philippines', 'Male');
insert into Students (id, city, country, gender) values (862, 'Skuratovskiy', 'Russia', 'Female');
insert into Students (id, city, country, gender) values (863, 'Otok', 'Croatia', 'Male');
insert into Students (id, city, country, gender) values (864, 'Hongmen', 'China', 'Male');
insert into Students (id, city, country, gender) values (865, 'Burnham', 'New Zealand', 'Female');
insert into Students (id, city, country, gender) values (866, 'Strasbourg', 'France', 'Female');
insert into Students (id, city, country, gender) values (867, 'El Paso', 'United States', 'Male');
insert into Students (id, city, country, gender) values (868, 'Karangsari', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (869, 'Dukuh', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (870, 'Gif-sur-Yvette', 'France', 'Male');
insert into Students (id, city, country, gender) values (871, 'Hayang', 'South Korea', 'Female');
insert into Students (id, city, country, gender) values (872, 'Kvänum', 'Sweden', 'Male');
insert into Students (id, city, country, gender) values (873, 'Quinta da Torre', 'Portugal', 'Male');
insert into Students (id, city, country, gender) values (874, 'Kalipucang', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (875, 'Podkamennaya Tunguska', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (876, 'Čortanovci', 'Serbia', 'Female');
insert into Students (id, city, country, gender) values (877, 'Kondangrege', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (878, 'Yongping', 'China', 'Female');
insert into Students (id, city, country, gender) values (879, 'Daniwato', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (880, 'Maishi', 'China', 'Male');
insert into Students (id, city, country, gender) values (881, 'Shinan', 'China', 'Female');
insert into Students (id, city, country, gender) values (882, 'Ledok', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (883, 'Minato', 'Japan', 'Female');
insert into Students (id, city, country, gender) values (884, 'Anlu', 'China', 'Female');
insert into Students (id, city, country, gender) values (885, 'Wonodadi', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (886, 'Jingmen', 'China', 'Female');
insert into Students (id, city, country, gender) values (887, 'Oslo', 'Norway', 'Male');
insert into Students (id, city, country, gender) values (888, 'Charlotte', 'United States', 'Female');
insert into Students (id, city, country, gender) values (889, 'Auch', 'France', 'Female');
insert into Students (id, city, country, gender) values (890, 'Chişinău', 'Moldova', 'Female');
insert into Students (id, city, country, gender) values (891, 'San Francisco', 'United States', 'Male');
insert into Students (id, city, country, gender) values (892, 'Okcheon', 'South Korea', 'Male');
insert into Students (id, city, country, gender) values (893, 'Lazo', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (894, 'Maodao', 'China', 'Male');
insert into Students (id, city, country, gender) values (895, 'Masaguisi', 'Philippines', 'Male');
insert into Students (id, city, country, gender) values (896, 'Atbasar', 'Kazakhstan', 'Male');
insert into Students (id, city, country, gender) values (897, 'Voyutychi', 'Ukraine', 'Female');
insert into Students (id, city, country, gender) values (898, 'Selaparang Timur', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (899, 'Cintawana', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (900, 'Ketanggi', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (901, 'Nakło nad Notecią', 'Poland', 'Male');
insert into Students (id, city, country, gender) values (902, 'Guanjiabao', 'China', 'Male');
insert into Students (id, city, country, gender) values (903, 'Andrushivka', 'Ukraine', 'Male');
insert into Students (id, city, country, gender) values (904, 'Keluke', 'China', 'Male');
insert into Students (id, city, country, gender) values (905, 'Kutapanjang', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (906, 'Ōta', 'Japan', 'Male');
insert into Students (id, city, country, gender) values (907, 'Médanos', 'Argentina', 'Female');
insert into Students (id, city, country, gender) values (908, 'Paty do Alferes', 'Brazil', 'Male');
insert into Students (id, city, country, gender) values (909, 'Chiconi', 'Mayotte', 'Female');
insert into Students (id, city, country, gender) values (910, 'Xiting', 'China', 'Female');
insert into Students (id, city, country, gender) values (911, 'Buda-Kashalyova', 'Belarus', 'Male');
insert into Students (id, city, country, gender) values (912, 'Kitahiroshima', 'Japan', 'Female');
insert into Students (id, city, country, gender) values (913, 'Thāru Shāh', 'Pakistan', 'Male');
insert into Students (id, city, country, gender) values (914, 'Tangtou', 'China', 'Male');
insert into Students (id, city, country, gender) values (915, 'Agua Fría', 'Honduras', 'Female');
insert into Students (id, city, country, gender) values (916, 'Niquelândia', 'Brazil', 'Male');
insert into Students (id, city, country, gender) values (917, 'Di Linh', 'Vietnam', 'Male');
insert into Students (id, city, country, gender) values (918, 'Yidu', 'China', 'Female');
insert into Students (id, city, country, gender) values (919, 'Nagcarlan', 'Philippines', 'Female');
insert into Students (id, city, country, gender) values (920, 'Sozopol', 'Bulgaria', 'Male');
insert into Students (id, city, country, gender) values (921, 'Sai', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (922, 'Ube', 'Japan', 'Male');
insert into Students (id, city, country, gender) values (923, 'Luleå', 'Sweden', 'Male');
insert into Students (id, city, country, gender) values (924, 'Taipalsaari', 'Finland', 'Female');
insert into Students (id, city, country, gender) values (925, 'Mafinga', 'Tanzania', 'Male');
insert into Students (id, city, country, gender) values (926, 'Pilcuyo', 'Peru', 'Female');
insert into Students (id, city, country, gender) values (927, 'Mirovka', 'Ukraine', 'Female');
insert into Students (id, city, country, gender) values (928, 'Oslo', 'Norway', 'Female');
insert into Students (id, city, country, gender) values (929, 'Al Bāriqīyah', 'Syria', 'Male');
insert into Students (id, city, country, gender) values (930, 'Cipicung', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (931, 'Krojo', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (932, 'Spitak', 'Armenia', 'Female');
insert into Students (id, city, country, gender) values (933, 'Nobres', 'Brazil', 'Male');
insert into Students (id, city, country, gender) values (934, 'Picton', 'New Zealand', 'Male');
insert into Students (id, city, country, gender) values (935, 'Rawa Satu', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (936, 'Nonghe', 'China', 'Female');
insert into Students (id, city, country, gender) values (937, 'Alor Setar', 'Malaysia', 'Female');
insert into Students (id, city, country, gender) values (938, 'Zaranj', 'Afghanistan', 'Female');
insert into Students (id, city, country, gender) values (939, 'Manaloal', 'Philippines', 'Male');
insert into Students (id, city, country, gender) values (940, 'Ipatinga', 'Brazil', 'Female');
insert into Students (id, city, country, gender) values (941, 'Častolovice', 'Czech Republic', 'Female');
insert into Students (id, city, country, gender) values (942, 'Ashikaga', 'Japan', 'Female');
insert into Students (id, city, country, gender) values (943, 'Panitan', 'Philippines', 'Female');
insert into Students (id, city, country, gender) values (944, 'Chatou', 'China', 'Male');
insert into Students (id, city, country, gender) values (945, 'Hua Sai', 'Thailand', 'Male');
insert into Students (id, city, country, gender) values (946, 'Dubna', 'Russia', 'Female');
insert into Students (id, city, country, gender) values (947, 'Kingscourt', 'Ireland', 'Male');
insert into Students (id, city, country, gender) values (948, 'Thủ Thừa', 'Vietnam', 'Female');
insert into Students (id, city, country, gender) values (949, 'Keboireng', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (950, 'Tumcon Ilawod', 'Philippines', 'Male');
insert into Students (id, city, country, gender) values (951, 'Huangyan', 'China', 'Female');
insert into Students (id, city, country, gender) values (952, 'Corral', 'Chile', 'Female');
insert into Students (id, city, country, gender) values (953, 'Pulong Sampalok', 'Philippines', 'Female');
insert into Students (id, city, country, gender) values (954, 'München', 'Germany', 'Male');
insert into Students (id, city, country, gender) values (955, 'El Cardo', 'Peru', 'Female');
insert into Students (id, city, country, gender) values (956, 'Umm as Sāhik', 'Saudi Arabia', 'Male');
insert into Students (id, city, country, gender) values (957, 'Maromitsa', 'Russia', 'Female');
insert into Students (id, city, country, gender) values (958, 'Sanmiaoqian', 'China', 'Female');
insert into Students (id, city, country, gender) values (959, 'Helsingborg', 'Sweden', 'Female');
insert into Students (id, city, country, gender) values (960, 'Siay', 'Philippines', 'Male');
insert into Students (id, city, country, gender) values (961, 'Zaysan', 'Kazakhstan', 'Male');
insert into Students (id, city, country, gender) values (962, 'Keyinhe', 'China', 'Male');
insert into Students (id, city, country, gender) values (963, 'Tsurusaki', 'Japan', 'Female');
insert into Students (id, city, country, gender) values (964, 'Sedkyrkeshch', 'Russia', 'Female');
insert into Students (id, city, country, gender) values (965, 'Zhouji', 'China', 'Male');
insert into Students (id, city, country, gender) values (966, 'Onitsha', 'Nigeria', 'Female');
insert into Students (id, city, country, gender) values (967, 'Piúma', 'Brazil', 'Male');
insert into Students (id, city, country, gender) values (968, 'Otun', 'Nigeria', 'Male');
insert into Students (id, city, country, gender) values (969, 'Bogdaniec', 'Poland', 'Female');
insert into Students (id, city, country, gender) values (970, 'Machico', 'Portugal', 'Male');
insert into Students (id, city, country, gender) values (971, 'Gaocheng', 'China', 'Male');
insert into Students (id, city, country, gender) values (972, 'Kharkhorin', 'Mongolia', 'Male');
insert into Students (id, city, country, gender) values (973, 'Pensacola', 'United States', 'Female');
insert into Students (id, city, country, gender) values (974, 'Guangshan Chengguanzhen', 'China', 'Female');
insert into Students (id, city, country, gender) values (975, 'Shaliu', 'China', 'Male');
insert into Students (id, city, country, gender) values (976, 'Meziměstí', 'Czech Republic', 'Female');
insert into Students (id, city, country, gender) values (977, 'Aduo', 'China', 'Male');
insert into Students (id, city, country, gender) values (978, 'Qiaoxi', 'China', 'Male');
insert into Students (id, city, country, gender) values (979, 'Tajumulco', 'Guatemala', 'Male');
insert into Students (id, city, country, gender) values (980, 'Belanting', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (981, 'Várzea', 'Portugal', 'Male');
insert into Students (id, city, country, gender) values (982, 'Kawasaki', 'Japan', 'Female');
insert into Students (id, city, country, gender) values (983, 'Lammi', 'Finland', 'Male');
insert into Students (id, city, country, gender) values (984, 'Xinó Neró', 'Greece', 'Male');
insert into Students (id, city, country, gender) values (985, 'Lyon', 'France', 'Female');
insert into Students (id, city, country, gender) values (986, 'Uwa', 'Indonesia', 'Male');
insert into Students (id, city, country, gender) values (987, 'Sui’an', 'China', 'Female');
insert into Students (id, city, country, gender) values (988, 'Ábidos', 'Brazil', 'Female');
insert into Students (id, city, country, gender) values (989, 'Ngilengan', 'Indonesia', 'Female');
insert into Students (id, city, country, gender) values (990, 'Rossosh’', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (991, 'Miasskoye', 'Russia', 'Male');
insert into Students (id, city, country, gender) values (992, 'Magsalangi', 'Philippines', 'Female');
insert into Students (id, city, country, gender) values (993, 'Aurora', 'Philippines', 'Male');
insert into Students (id, city, country, gender) values (994, 'Xitieshan', 'China', 'Female');
insert into Students (id, city, country, gender) values (995, 'Křížová', 'Czech Republic', 'Male');
insert into Students (id, city, country, gender) values (996, 'Jilib', 'Somalia', 'Male');
insert into Students (id, city, country, gender) values (997, 'Jiabeiyan', 'China', 'Female');
insert into Students (id, city, country, gender) values (998, 'Smyshlyayevka', 'Russia', 'Female');
insert into Students (id, city, country, gender) values (999, 'Honglin', 'China', 'Female');
insert into Students (id, city, country, gender) values (1000, 'Caohe', 'China', 'Female');

